version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: customers/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app   # live reload Django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"

    depends_on:
      - backend
      - frontend
