version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: customers/Dockerfile
    volumes:
      - ./backend:/app/backend   # live reload Django
      - ./customers:/app/customers
    ports:
      - "8002:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules        # avoid overwriting node_modules
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # for hot reload in Docker
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

